\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Survival Analysis HW 1},
  pdfauthor={David Coomes},
  pdfborder={0 0 0},
  breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs}
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-2}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{Survival Analysis HW 1}
\author{David Coomes}
\date{Due 1/23/2020}

\begin{document}
\maketitle

\#\#Problem 1.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  Individual A is administratively (right) censored at age 60 (30 years
  after the beginning of the study), and contributes 30 years to left
  truncation.
\item
  Individual B experiences interval censoring from the time they
  developed breast cancer after the fourth exam until they were
  diagnosed with breast cancer at the fifth exam. They contribute 40
  years to left truncation in this study.
\item
  Individual C is right censored at age 61 due to death, and they
  contribute 50 years to left truncation.
\item
  Individual D is right censored at age 54 (the time of their last
  clinical exam) due to loss to follow up. They contribute 42 years to
  left truncation.
\end{enumerate}

If we were interested in studying the time from enrollment into study
until onset of breast cancer instead of age at onset, this would change
my answers to when each individual contributes to left truncation, but
it would not change the answers to when they were censored. In that case
(time from enrollment), there would be no left truncation present.

\#\#Problem 2.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  This data set is affected by left truncation. By sampling a set of
  current Crohn's disease patients at a specific time, we are more
  likely to sample those individuals who will have a longer period
  between diagnosis of disease and the outcome of interest. For
  censoring, if we are able to follow all recruited patients for 10
  years, and there is no loss to follow up, then we will likely have
  some administrative censoring at the end of the study. If, by some
  chance, all those who were selected had the outcome, then there would
  be no censoring.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  I do not necessarily agree with this statement. If A and T are totally
  independent, then I would agree that the observed ages at diagnosis
  are not affected by selection bias. But, if there is an association
  between these two, then I would argue that there is some selection
  bias on age.
\end{enumerate}

\#\#Problem 3.

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\item
  The study population was 312 primary biliary cirrhosis patients
  enrolled in two RCTs at the Mayo Clinic.
\item
  The initiating event was the date the patient was determined eligible
  for the clinical trials.
\item
  The terminating event was death from any cause.
\item
  The time scale for this study was in months.
\item
  The causes of censoring were loss to follow up, liver transplant, and
  end of the study.
\item
  The end of the study was not likely related to the outcome in this
  study. It's difficult to know whether loss to follow up is related to
  death, but I can't think of a strong reason why it would be so in this
  case. Liver transplantation may be related to the outcome because
  those that were worse off (closer to dying) may have been more likely
  to receive a transplant, but it is difficult to know without knowing
  the rules regarding transplant priority.
\item
  For those in the `Low' category, approximately 15\% die within the
  first five years. This number is almost 50\% for those in the `Medium'
  category, and about 80\% for those in the `High' category.
\end{enumerate}

\#\#Problem 4.

\begin{verbatim}
## Warning: package 'survival' was built under R version 3.6.2
\end{verbatim}

\begin{verbatim}
## Warning: package 'flexsurv' was built under R version 3.6.2
\end{verbatim}

\begin{verbatim}
## Warning: package 'msm' was built under R version 3.6.2
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'msm'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:flexsurv':
## 
##     qgeneric
\end{verbatim}

\begin{verbatim}
##    id clinic prison dose time event
## 1   1      1      0   50  428     1
## 2   2      1      1   55  275     1
## 3   3      1      0   55  262     1
## 4   4      1      0   30  183     1
## 5   5      1      1   65  259     1
## 6   6      1      0   55  714     1
## 7   7      1      1   65  438     1
## 8   8      1      1   60  796     0
## 9   9      1      0   50  892     1
## 10 10      1      1   65  393     1
\end{verbatim}

\begin{verbatim}
## [1] 402.5714
\end{verbatim}

\begin{verbatim}
## [1] 367.5
\end{verbatim}

\begin{verbatim}
## [1] 0.3697479
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\tightlist
\item
  The mean follow up time was 402.6 days and the median follow up time
  was 367.5 days. The proportion of censored individuals was 37.0\%.
\end{enumerate}

\begin{verbatim}
## [1] ### SUMMARY OF FITTED EXPONENTIAL MODEL ###
## [1] 
## [1] MODEL FIT SUMMARIES
## [1] 
## [1] Total number of observations: 238  
## [1] Number of events observed: 150  
## [1] Number of model parameters: 1  
## [1] Maximized loglikelihood value: -1118.93  
## [1] 
## [1] INFERENCE ON MODEL COEFFICIENTS
## [1] 
##        estimate ci.lower ci.upper      se
## lambda  0.00157  0.00132  0.00182 0.00013
\end{verbatim}

\begin{verbatim}
## [1] ### SUMMARY OF FITTED WEIBULL MODEL ###
## [1] 
## [1] MODEL FIT SUMMARIES
## [1] 
## [1] Total number of observations: 238  
## [1] Number of events observed: 150  
## [1] Number of model parameters: 2  
## [1] Maximized loglikelihood value: -1114.92  
## [1] 
## [1] INFERENCE ON MODEL COEFFICIENTS
## [1] 
##        estimate ci.lower ci.upper      se
## lambda  0.00162  0.00141  0.00183 0.00011
## p       1.22642  1.06035  1.39249 0.08473
\end{verbatim}

\begin{verbatim}
## [1] ### SUMMARY OF FITTED GENERALIZED GAMMA MODEL ###
## [1] 
## [1] MODEL FIT SUMMARIES
## [1] 
## [1] Total number of observations: 238  
## [1] Number of events observed: 150  
## [1] Number of model parameters: 3  
## [1] Maximized loglikelihood value: -1114.36  
## [1] 
## [1] INFERENCE ON MODEL COEFFICIENTS
## [1] 
##       estimate ci.lower ci.upper      se
## mu     6.55024  6.26940  6.83109 0.14329
## sigma  0.65950  0.32605  0.99296 0.17013
## Q      1.46819  0.38478  2.55159 0.55277
\end{verbatim}

\begin{enumerate}
\def\labelenumi{(\alph{enumi})}
\setcounter{enumi}{1}
\item
\end{enumerate}

\begin{longtable}[]{@{}llllll@{}}
\toprule
Model & Parameter & Estimate & 95\% Lower & 95\% Upper & Maximum
loglikelihood\tabularnewline
\midrule
\endhead
Exponential & \(\lambda\) & 0.00157 & 0.00132 & 0.00182 &
-1118.93\tabularnewline
Weibull & \(\lambda\) & 0.00162 & 0.00141 & 0.00183 &
-1114.92\tabularnewline
& \(P\) & 1.226 & 1.060 & 1.392 &\tabularnewline
Generalized Gamma & \(\mu\) & 6.550 & 6.269 & 6.831 &
-1114.36\tabularnewline
& \(\Sigma\) & 0.660 & 0.326 & 0.993 &\tabularnewline
& \(Q\) & 1.468 & 0.385 & 2.552 &\tabularnewline
\bottomrule
\end{longtable}

\end{document}
